// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyrdaeschkrgxejkwmlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5cmRhZXNjaGtyZ3hlamt3bWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NzM1NDYsImV4cCI6MjA5MTA0OTU0Nn0.N1fbqogOXIpiOhcql9gP9mxuFk_YajvEOGmGxWrosiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});